stages:
  - test

test:
  stage: test
  image: node:alpine
  script:
    - yarn
    - yarn test
  artifacts:
    reports:
      junit: junit.xml
      cobertura: coverage/cobertura-coverage.xml
  tags:
    - docker
