stages:
  - test
  - publish

test:
  stage: test
  image: node:alpine
  script:
    - yarn
    - yarn test
  artifacts:
    reports:
      junit: junit.xml
      cobertura: coverage/cobertura-coverage.xml
  tags:
    - docker

publish:
  when: manual
  stage: publish
  image: node:alpine
  script:
    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
    - npm publish
  tags:
    - docker
